language: java
jdk: openjdk11

jobs:
  include:
    - stage: Tests
      name: Openweather API tests
      script: ./gradlew clean testApi -DapiToken=$API_TOKEN
    - name: Wiktionary WEB tests using Chrome browser
      addons:
        chrome: stable
      script: ./gradlew clean testWeb -Dbrowser=chrome -Dheadless=true
    - name: Wiktionary WEB tests using Firefox browser
      addons:
        firefox: latest
      script: ./gradlew clean testWeb -Dbrowser=firefox -Dheadless=true
