language: java
jdk: openjdk11

addons:
  chrome: stable
  firefox: latest

jobs:
  include:
    - stage: test
      script: ./gradlew clean testApi
    - #
      script: ./gradlew clean testWeb -Dbrowser=chrome -Dheadless=true
    - #
      script: ./gradlew clean testWeb -Dbrowser=firefox -Dheadless=true
